name: 'Install packages'
description: 'Install required packages'

runs:
  using: "composite"
  steps:
    - name: Install All Linux Dependencies (Raylib + Tools)
      shell: bash
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt install -y \
          ninja-build xdotool openbox \
          libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev \
          libxi-dev libgl1-mesa-dev libglu1-mesa-dev \
          libasound2-dev libpulse-dev libxkbcommon-dev \
          libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 \
          libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 \
          libxcb-xinerama0 libxcb-xfixes0
          
        # Fix pentru testele de memorie ale profesorului
        sudo sysctl vm.mmap_rnd_bits=28

    - name: Install valgrind
      shell: bash
      if: runner.os == 'Linux' && matrix.runs_valgrind == true
      run: |
        sudo apt install -y --no-install-recommends valgrind
