name: 'Install packages'
description: 'Install required packages'

runs:
  using: "composite"
  steps:
    # 1. Chemăm folderul nou creat (exact cum face colegul tău)
    - name: Install common Linux Dependencies
      if: runner.os == 'Linux'
      uses: ./.github/actions/install-linux-deps

    # 2. Varianta de la prof (am lăsat ninja-build, am adăugat xdotool/openbox pt. teste grafice)
    - name: Install Linux Dependencies
      shell: bash
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install -y ninja-build xdotool openbox
        # Fix pentru LLVM/Clang necesar în template
        sudo sysctl vm.mmap_rnd_bits=28

    # 3. Valgrind-ul de la prof (neschimbat)
    - name: Install valgrind
      shell: bash
      if: runner.os == 'Linux' && matrix.runs_valgrind == true
      run: |
        sudo apt-get install -y --no-install-recommends valgrind
